# Generated by Django 3.2.9 on 2022-02-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cmsApp', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='customer_Credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
